"""CMD-GR7: a guard generated by ga rlo keeps the session on its channel (ga mail) and sends its own denies out.

D1: the replay -- ReadNotifications denied -> react use_tool ga.mail.read; a deny leaves an outbox event; a real
    `ga mail send --guard-event` of it is delivered as a valid report/2 (and the worker rule's command line runs as is).
D2: mutations killed -- the mail grant missing, the grant not pinned to the repo, the outbox not written.
D3: a venv with the old PIN's marker and a guard with the new PIN: the next call installs once, the second does not;
    a failing install denies with a reason that names the channel still allowed.
D4: a working tree with model v1 and a guard ref with v2 is judged by v2 (the record names the ref sha); an unreadable
    ref denies all but the channel; the fetch is bounded; mutants (working tree used, unbounded fetch) are killed.
"""
import importlib.util
import json
import os
import shutil
import subprocess
import sys
import tempfile
import time
import unittest
from pathlib import Path
from unittest import mock

from ga.rlo import remote

from .test_remote import RemoteBase, guard_py
from .world import GIT_ENV, run_cli

PY = sys.executable  # a python with rlo installed stands for the venv install.sh makes
GITENV = dict(GIT_ENV, GIT_CONFIG_GLOBAL=os.devnull, GIT_TERMINAL_PROMPT="0")


def sh(cwd, *argv, check=True, env=None):
    return subprocess.run(list(argv), cwd=cwd, check=check, capture_output=True, text=True,
                          env=dict(os.environ, **GITENV, **(env or {})))


def venv(where: Path, pin: str | None) -> Path:
    """A stand-in venv: its python is this one (rlo installed), with the marker of ``pin``."""
    (where / "bin").mkdir(parents=True)
    py = where / "bin" / "python"
    py.write_text(f"#!/bin/sh\nexec {PY} \"$@\"\n")
    py.chmod(0o755)
    if pin:
        (where / f".pinned-{pin}").write_text("")
    return where


class Worker:
    """A remote worker's checkout with the generated guard, called as Claude Code calls it (bash guard.sh, JSON)."""

    def __init__(self, tmp: Path, repo: Path, venv_dir: Path, path_extra: Path | None = None):
        self.tmp, self.repo, self.venv = tmp, repo, venv_dir
        self.home = tmp / "home"
        self.home.mkdir(exist_ok=True)
        self.path_extra = path_extra
        self.n = 0

    def call(self, tool: str, inp: dict, env: dict | None = None) -> tuple[str | None, str]:
        self.n += 1
        t = self.tmp / f"t{self.n}.jsonl"
        remote.transcript([("Bash", {"command": "ls"}, True, time.time() * 1000 - 5000)], t)
        data = {"session_id": "s", "transcript_path": str(t), "cwd": str(self.repo), "permission_mode": "default",
                "hook_event_name": "PreToolUse", "tool_name": tool, "tool_input": inp, "tool_use_id": f"call{self.n}"}
        path = os.environ["PATH"] if self.path_extra is None else f"{self.path_extra}:{os.environ['PATH']}"
        e = {"PATH": path, "HOME": str(self.home), "CLAUDE_PROJECT_DIR": str(self.repo), remote.VENV_VAR: str(self.venv),
             **GITENV, **(env or {})}
        p = subprocess.run(["bash", str(self.repo / "ops/rlo/guard.sh")], input=json.dumps(data), capture_output=True,
                           text=True, env=e, cwd=str(self.repo), timeout=300)
        assert p.returncode == 0, p.stderr
        out = json.loads(p.stdout) if p.stdout.strip() else {}
        hso = out.get("hookSpecificOutput") or {}
        return hso.get("permissionDecision"), hso.get("permissionDecisionReason", "")

    def record(self) -> list[dict]:
        p = self.home / ".rlo" / "W1.jsonl"
        return [json.loads(x) for x in p.read_text().splitlines()] if p.exists() else []

    def events(self) -> list[Path]:
        return sorted((self.repo / remote.OUTBOX).glob("*.jsonl"))


class Tmp(unittest.TestCase):
    def setUp(self):
        self.tmp = Path(tempfile.mkdtemp(prefix="ga-rlo-gr7-"))
        self.addCleanup(shutil.rmtree, self.tmp, True)


# ------------------------------------------------------------------------------------------------ D1

class MailTest(Tmp):
    def setUp(self):
        super().setUp()
        self.origin = self.tmp / "origin.git"
        sh(self.tmp, "git", "init", "-q", "--bare", str(self.origin))
        self.repo = self.tmp / "work"
        sh(self.tmp, "git", "clone", "-q", str(self.origin), str(self.repo))
        remote.write(self.repo, "W1")
        pin = remote.pin_of(self.repo / "ops/rlo/install.sh")
        bin_ = self.tmp / "bin"
        bin_.mkdir()
        ga = bin_ / "ga"  # `ga` on PATH, as `pip install ga-sdk` makes it
        ga.write_text(f"#!/bin/sh\nexec {PY} -m ga \"$@\"\n")
        ga.chmod(0o755)
        self.w = Worker(self.tmp, self.repo, venv(self.tmp / "venv", pin), bin_)

    def test_read_notifications_denied_reacts_with_ga_mail_read(self):
        d = {n: (ok, detail) for n, ok, detail in remote.replay(self.repo, sys.prefix)}
        ok, detail = d["W1 v1 model: ReadNotifications"]
        self.assertTrue(ok, detail)
        self.assertIn("tool=ga.mail.read", detail)
        self.assertIn("outbox event is a valid report/2", detail)
        self.assertTrue(all(ok for ok, _ in d.values()), [n for n, (ok, _) in d.items() if not ok])

    def test_a_deny_leaves_an_outbox_event_that_ga_mail_sends_as_report2(self):
        dec, why = self.w.call("WebFetch", {"url": "https://example.invalid/"})
        self.assertEqual(dec, "deny")
        [ev] = self.w.events()
        self.assertEqual((self.repo / remote.OUTBOX / ".gitignore").read_text(), "*\n")  # never committed by accident
        self.assertEqual(sh(self.repo, "git", "status", "--porcelain").stdout.count(".ga/"), 0)
        lines = [json.loads(x) for x in ev.read_text().splitlines()]
        self.assertEqual([x["kind"] for x in lines], ["guard", "state"])  # rlo's own record line, then the source
        self.assertEqual(lines[0]["result"]["rule"], "A1")
        self.assertEqual(lines[1]["labels"]["guard_source"], "worktree")
        # the worker rule's command line, run as the worker runs it: through the guard first, then bash
        rel = ev.relative_to(self.repo).as_posix()
        cmd = f"ga mail send --repo . --to hub --from W1 --guard-event {rel} --re CMD-GR7 && rm -f {rel}"
        self.assertEqual(self.w.call("Bash", {"command": cmd}), (None, ""))
        p = sh(self.repo, "bash", "-c", cmd, env={"PATH": f"{self.tmp / 'bin'}:{os.environ['PATH']}"}, check=False)
        self.assertEqual(p.returncode, 0, p.stderr)
        self.assertFalse(ev.exists())  # sent, then removed: no second send of the same event
        hub = self.tmp / "hub"
        sh(self.tmp, "git", "clone", "-q", str(self.origin), str(hub))
        p = sh(hub, PY, "-m", "ga", "mail", "read", "--repo", ".", "--as", "hub", "--json")
        [msg] = [json.loads(x) for x in p.stdout.splitlines()]
        self.assertEqual((msg["schema"], msg["valid"], msg["from"]), ("report/2", True, "W1"))
        self.assertIn("blocked by guard rlo", msg["text"])
        self.assertIn("A1", msg["text"])

    def test_pinned_and_unpinned_ga_mail(self):
        ok = ["ga mail read --repo . --as W1", f"ga mail read --repo {self.repo} --as W1 --json",
              "ga mail scan --repo ./", "ga mail send --repo . --to hub --from W1 report.md",
              "ga mail send --repo . --remote origin --to hub --from W1 --guard-event .ga/mailbox/outbox/a.jsonl --re CMD-X1"]
        bad = ["ga mail read --repo .. --as W1", "ga mail read --as W1", "ga mail read --repo . --remote up --as W1",
               "ga mail read --repo . --as W1 > /tmp/x", "ga mail read --repo . --as 'W1'", "ga mail read --repo . --as W1 --as W2",
               "ga mail send --repo . --to hub --guard-event /etc/passwd --re CMD-X1",
               "ga mail send --repo . --to hub --guard-event .ga/mailbox/outbox/a.jsonl --re X && rm -f README.md",
               "ga mail send --repo . --to hub a.md b.md", "ga mail read --repo .;rm -rf x", "ls && ga mail scan --repo /",
               "cd /tmp && ga mail scan --repo .", "ga mail scan --repo . --repo /", "ga mail purge --repo ."]
        for cmd in ok:
            with self.subTest(cmd=cmd):
                self.assertEqual(self.w.call("Bash", {"command": cmd})[0], None)
        for cmd in bad:
            with self.subTest(cmd=cmd):
                dec, why = self.w.call("Bash", {"command": cmd})
                self.assertEqual(dec, "deny")
                self.assertIn("rlo guard (channel pin)", why)
        for cmd in ("echo ga mail", 'grep -n "ga mail" README.md', "git log --grep=ga-mail"):
            with self.subTest(cmd=cmd):  # ga mail as an argument is not a ga mail command
                self.assertEqual(self.w.call("Bash", {"command": cmd})[0], None)


# ------------------------------------------------------------------------------------------------ D2

class MutationTest(RemoteBase):
    def setUp(self):
        super().setUp()
        self.init()

    def doctor_failed(self):
        return super().doctor_failed()

    def test_good(self):
        self.assertEqual(self.doctor_failed(), set())

    def test_mail_grant_missing(self):
        self.edit("ops/rlo/guard.py", '"mcp__claude-code-remote__send_message","ga.mail.send"]',
                  '"mcp__claude-code-remote__send_message"]')
        bad = self.doctor_failed()
        self.assertIn("remote.preset", bad)
        self.assertIn("remote.replay.model without send_message: send_message", bad)  # no use_tool ga.mail.send

    def test_mail_grant_missing_from_the_preset(self):
        with mock.patch.object(remote, "GRANTS", tuple(g for g in remote.GRANTS if g != "ga.mail.send")):
            d = self.tmp / "w2"
            d.mkdir()
            remote.write(d, "W1")
            res = {n: ok for n, ok, _ in remote.replay(d, sys.prefix)}
        self.assertFalse(res["model without send_message: send_message"])

    def test_mail_label_dropped_from_the_model(self):
        p = self.repo / "ops/rlo/model.json"
        m = json.loads(p.read_text())
        m["specs"] = [s for s in m["specs"] if s["name"] != "ga.mail.read"]
        p.write_text(json.dumps(m))
        bad = self.doctor_failed()
        self.assertIn("remote.preset", bad)
        self.assertIn("remote.replay.W1 v1 model: ReadNotifications", bad)  # falls back to issue_read

    def test_grant_not_pinned_to_the_repo(self):
        self.edit("ops/rlo/guard.py", 'if "--repo" not in seen or real(cwd, seen["--repo"]) != real(DIR, CONF["channel_repo"]):',
                  'if "--repo" not in seen:')
        bad = self.doctor_failed()
        self.assertIn("remote.preset", bad)
        self.assertTrue({"remote.replay.ga mail read, another repo",
                         "remote.replay.install fails: ga mail read, another repo"} <= bad, bad)

    def test_outbox_not_written(self):
        for call in ("outbox(mine + [state], str(rule or \"deny\"))", "outbox([line], rule)"):
            with self.subTest(call=call):
                good = guard_py(self.repo).read_text()
                self.edit("ops/rlo/guard.py", call, "None")
                bad = self.doctor_failed()
                self.assertIn("remote.preset", bad)
                cases = {"remote.replay.A1 WebFetch"} if call.startswith("outbox(mine") else {
                    "remote.replay.install fails: WebFetch", "remote.replay.ga mail read, another repo"}
                self.assertTrue(cases <= bad, bad)
                guard_py(self.repo).write_text(good)

    def test_outbox_rule_removed(self):
        self.edit("ops/rlo/PROMPT.md", remote.OUTBOX_RULE, "Keep your denies.")
        self.assertIn("remote.preset", self.doctor_failed())


# ------------------------------------------------------------------------------------------------ D3

FAKE_INSTALL = """#!/usr/bin/env bash
set -u
PIN="{pin}"
VENV="${{GA_RLO_VENV:-$HOME/.cache/ga-rlo-venv}}"
MARK="$VENV/.pinned-$PIN"
[ -f "$MARK" ] && exit 0
echo "$PIN" >> {log}
[ -n "${{FAIL_INSTALL:-}}" ] && exit 1
touch "$MARK"
"""


class PinMarkerTest(Tmp):
    OLD, NEW = "1" * 40, "2" * 40

    def setUp(self):
        super().setUp()
        self.repo = self.tmp / "work"
        self.repo.mkdir()
        remote.write(self.repo, "W1")
        self.log = self.tmp / "install.log"
        (self.repo / "ops/rlo/install.sh").write_text(FAKE_INSTALL.format(pin=self.NEW, log=self.log))
        self.w = Worker(self.tmp, self.repo, venv(self.tmp / "venv", self.OLD))  # rlo of the old PIN, marked

    def installs(self) -> list[str]:
        return self.log.read_text().split() if self.log.exists() else []

    def test_the_new_pin_is_installed_once(self):
        self.assertEqual(self.w.call("Bash", {"command": "ls"}), (None, ""))
        self.assertEqual(self.installs(), [self.NEW])
        self.assertTrue((self.w.venv / f".pinned-{self.NEW}").exists())
        self.assertEqual(self.w.call("Bash", {"command": "ls"}), (None, ""))
        self.assertEqual(self.installs(), [self.NEW])  # the second call does not reinstall

    def test_install_failure_denies_and_names_the_channel(self):
        dec, why = self.w.call("Bash", {"command": "ls"}, env={"FAIL_INSTALL": "1"})
        self.assertEqual(dec, "deny")
        self.assertIn(f"rlo guard (fail closed): rlo {self.NEW[:7]} not installed and install failed", why)
        for t in remote.CHANNEL_TOOLS:
            self.assertIn(t, why)
        self.assertIn("ga mail send|read|scan --repo .", why)
        self.assertEqual(remote.react_of(why)["cause"], "install_failed")
        # ... and they are allowed indeed, while the install keeps failing
        self.assertEqual(self.w.call("ReadNotifications", {}, env={"FAIL_INSTALL": "1"}), (None, ""))
        self.assertEqual(self.w.call("Bash", {"command": "ga mail read --repo . --as W1"}, env={"FAIL_INSTALL": "1"}),
                         (None, ""))
        self.assertEqual(len(self.installs()), 3)  # tried on each call: the next call can still recover
        self.assertEqual(len(self.w.events()), 1)  # the one deny is in the outbox

    def test_mutant_venv_only_check_is_killed(self):
        """GR6's guard reinstalled only when the venv was missing: with that check the old rlo keeps judging."""
        g = guard_py(self.repo)
        good = g.read_text()
        old = 'if os.path.isfile(marker) and os.access(os.path.join(VENV, "bin", "python"), os.X_OK):'
        self.assertIn(old, good)
        g.write_text(good.replace(old, 'if os.access(os.path.join(VENV, "bin", "python"), os.X_OK):'))
        self.w.call("Bash", {"command": "ls"})
        self.assertEqual(self.installs(), [])  # what test_the_new_pin_is_installed_once rejects


# ------------------------------------------------------------------------------------------------ D4

class GuardRefTest(Tmp):
    """origin/guard holds the guard; the running session's working tree has model v1, the ref moves to v2."""

    def setUp(self):
        super().setUp()
        self.origin = self.tmp / "origin.git"
        sh(self.tmp, "git", "init", "-q", "--bare", str(self.origin))
        seed = self.tmp / "seed"
        sh(self.tmp, "git", "clone", "-q", str(self.origin), str(seed))
        sh(seed, "git", "checkout", "-q", "-b", "guard")
        remote.write(seed, "W1", guard_ref="origin/guard", fetch_every_min=5)
        self.v2 = (seed / "ops/rlo/model.json").read_text()
        m = json.loads(self.v2)
        m["specs"] = [s for s in m["specs"] if s["name"] != "ReadNotifications"]  # v1: W1's first model
        (seed / "ops/rlo/model.json").write_text(json.dumps(m))
        sh(seed, "git", "add", "-A")
        sh(seed, "git", "commit", "-q", "-m", "guard v1")
        sh(seed, "git", "push", "-q", "origin", "guard")
        self.repo = self.tmp / "work"
        sh(self.tmp, "git", "clone", "-q", "-b", "guard", str(self.origin), str(self.repo))  # the session: v1
        (seed / "ops/rlo/model.json").write_text(self.v2)
        sh(seed, "git", "commit", "-q", "-am", "guard v2: ReadNotifications back")
        sh(seed, "git", "push", "-q", "origin", "guard")
        self.v2_sha = sh(seed, "git", "rev-parse", "HEAD").stdout.strip()
        # a git on PATH that logs each fetch the guard makes
        bin_ = self.tmp / "bin"
        bin_.mkdir()
        self.fetches = self.tmp / "fetch.log"
        real = shutil.which("git")
        (bin_ / "git").write_text(f"#!/bin/sh\n[ \"$3\" = fetch ] && echo fetch >> {self.fetches}\nexec {real} \"$@\"\n")
        (bin_ / "git").chmod(0o755)
        pin = remote.pin_of(self.repo / "ops/rlo/install.sh")
        self.w = Worker(self.tmp, self.repo, venv(self.tmp / "venv", pin), bin_)

    def n_fetches(self) -> int:
        return len(self.fetches.read_text().split()) if self.fetches.exists() else 0

    def test_judged_by_the_ref_not_the_working_tree(self):
        here = json.loads((self.repo / "ops/rlo/model.json").read_text())
        self.assertNotIn("ReadNotifications", {s["name"] for s in here["specs"]})  # v1 here
        self.assertEqual(self.w.call("ReadNotifications", {}), (None, ""))  # v2 there: allowed
        state = [x for x in self.w.record() if x["kind"] == "state"][-1]["labels"]
        self.assertEqual(state, {"guard_source": "ref", "guard_ref": "origin.guard", "guard_sha": self.v2_sha})
        self.assertEqual(self.n_fetches(), 1)

    def test_mutant_working_tree_used_is_killed(self):
        g = guard_py(self.repo)
        g.write_text(g.read_text().replace('    if not ref:\n', '    if True:\n', 1))
        dec, why = self.w.call("ReadNotifications", {})
        self.assertEqual(dec, "deny")  # judged by v1: what the test above rejects
        self.assertIn("(A1)", why)

    def test_the_fetch_is_bounded(self):
        for _ in range(3):
            self.w.call("Bash", {"command": "ls"})
        self.assertEqual(self.n_fetches(), 1)
        stamp = self.w.home / ".rlo" / "W1.fetch"
        stamp.write_text(f"{time.time() - 5 * 60 - 1:.3f}\n")  # the bound has passed
        self.w.call("Bash", {"command": "ls"})
        self.assertEqual(self.n_fetches(), 2)

    def test_mutant_unbounded_fetch_is_killed(self):
        g = guard_py(self.repo)
        old = '    if 0 <= now - last < CONF["fetch_every_s"]:\n        return\n'
        self.assertIn(old, g.read_text())
        g.write_text(g.read_text().replace(old, ""))
        for _ in range(3):
            self.w.call("Bash", {"command": "ls"})
        self.assertEqual(self.n_fetches(), 3)  # what test_the_fetch_is_bounded rejects

    def test_unreadable_ref_denies_all_but_the_channel(self):
        sh(self.origin, "git", "update-ref", "-d", "refs/heads/guard")      # the branch is gone upstream ...
        sh(self.repo, "git", "update-ref", "-d", "refs/remotes/origin/guard")  # ... and here
        dec, why = self.w.call("Bash", {"command": "ls"})
        self.assertEqual(dec, "deny")
        self.assertIn("rlo guard (fail closed): guard ref origin/guard unreadable", why)
        self.assertEqual(remote.react_of(why)["cause"], "ref_unreadable")
        for tool, inp in remote.PLUMBING_CALLS:
            with self.subTest(tool=tool):
                self.assertEqual(self.w.call(tool, inp), (None, ""))
        self.assertEqual(self.w.call("Bash", {"command": "ga mail read --repo . --as W1"}), (None, ""))
        self.assertEqual(self.w.call("Bash", {"command": "ga mail read --repo / --as W1"})[0], "deny")
        self.assertEqual(self.w.call("WebFetch", {"url": "u"})[0], "deny")
        self.assertEqual([x["cause"] for x in self.w.record() if x["kind"] == "channel"], ["ref_unreadable"] * 6)

    def test_a_pin_moved_on_the_ref_installs_at_the_next_call(self):
        """BD-238: the merge that moves the PIN reaches a running session at its next tool call."""
        seed = self.tmp / "seed"
        log = self.tmp / "install.log"
        (seed / "ops/rlo/install.sh").write_text(FAKE_INSTALL.format(pin="3" * 40, log=log))
        sh(seed, "git", "commit", "-q", "-am", "move the PIN")
        sh(seed, "git", "push", "-q", "origin", "guard")
        self.assertEqual(self.w.call("Bash", {"command": "ls"}), (None, ""))
        self.assertEqual(log.read_text().split(), ["3" * 40])
        self.assertTrue((self.w.venv / f".pinned-{'3' * 40}").exists())

    def test_doctor_and_problems_on_a_ref_guard(self):
        # the working tree's model is v1 (no ReadNotifications): doctor checks the files that are here
        self.assertEqual(remote.problems(self.repo), ["model.json: plumbing tool ReadNotifications is missing (S2)"])
        rc, out, _ = run_cli("doctor", "--profile", "remote", "--work-repo", str(self.repo), "--venv", sys.prefix,
                             "--json")
        bad = [c for c in json.loads(out)["checks"] if not c["ok"]]
        self.assertEqual({c["check"] for c in bad} - {"remote.preset", "remote.replay.plumbing ReadNotifications",
                                                      "person.settings"}, set(), bad)


# ------------------------------------------------------------------------------------------------ S3, units

class UpgradeMoveTest(Tmp):
    def test_a_pre_gr7_guard_gets_the_move_printed_and_nothing_runs(self):
        amp = self.tmp / "amp"
        (amp / "ops/rlo").mkdir(parents=True)
        (amp / "ops/rlo/install.sh").write_text(f'#!/usr/bin/env bash\nPIN="{remote._pins.PINS["rlo"][3]}"\n')
        (amp / "ops/rlo/guard.sh").write_text('#!/usr/bin/env bash\nREC="$HOME/.rlo/w1.jsonl"\n')
        (amp / "ops/rlo/w1_guard.json").write_text("{}")
        before = sorted((p.name, p.read_text()) for p in (amp / "ops/rlo").iterdir())
        rc, out, err = run_cli("upgrade-remote", "--work-repo", str(amp), "--hub", "AMP", "--guard-ref", "origin/main")
        self.assertEqual(rc, 0, err)
        self.assertEqual(sorted((p.name, p.read_text()) for p in (amp / "ops/rlo").iterdir()), before)
        self.assertIn("HUMAN_QUEUE", out)
        cmds = [x.strip() for x in out.splitlines() if x.startswith("  ")]
        self.assertTrue(cmds[0].startswith("ga rlo init --profile remote ") and "--name w1 --hub AMP" in cmds[0])
        self.assertIn("--guard-ref origin/main --force", cmds[0])
        self.assertTrue(any(c.endswith("rm -q ops/rlo/w1_guard.json") for c in cmds))
        self.assertTrue(cmds[-1].endswith("push origin HEAD:refs/heads/main"))
        # what the person runs first, run here: then the guard is a GR7 guard and nothing is owed
        from shlex import split
        rc, _, err = run_cli(*split(cmds[0])[2:])
        self.assertEqual(rc, 0, err)
        rc, out, _ = run_cli("upgrade-remote", "--work-repo", str(amp), "--hub", "AMP")
        self.assertIn("nothing to do", out)

    def test_bad_options_are_refused(self):
        for argv in (["--guard-ref", "main"], ["--hub", "a b"], ["--channel-repo", "-x"]):
            with self.subTest(argv=argv):
                (self.tmp / "r/ops/rlo").mkdir(parents=True, exist_ok=True)
                (self.tmp / "r/ops/rlo/install.sh").write_text('PIN="1111111"\n')
                rc, _, err = run_cli("upgrade-remote", "--work-repo", str(self.tmp / "r"), *argv)
                self.assertEqual(rc, 2, err)


class GuardModuleTest(Tmp):
    """guard.py's pieces, imported from the generated file."""

    def load(self, **kw):
        repo = self.tmp / f"w{len(list(self.tmp.iterdir()))}"
        repo.mkdir()
        remote.write(repo, "W-1", **kw)
        spec = importlib.util.spec_from_file_location("guard_under_test", repo / "ops/rlo/guard.py")
        mod = importlib.util.module_from_spec(spec)
        with mock.patch.dict(os.environ, {"CLAUDE_PROJECT_DIR": str(repo)}):
            spec.loader.exec_module(mod)
        return repo, mod

    def test_conf_round_trip_and_sender(self):
        repo, mod = self.load(hub="AMP", channel_repo="mail", guard_ref="origin/claude/w1-guard", fetch_every_min=2)
        self.assertEqual(mod.CONF["sender"], "W_1")  # ga mail senders carry no '-'
        self.assertEqual(mod.CONF["guard_ref"], {"remote": "origin", "branch": "claude/w1-guard"})
        self.assertEqual(mod.CONF["fetch_every_s"], 120)
        self.assertEqual(remote.conf_of((repo / "ops/rlo/guard.py").read_text()), mod.CONF)
        self.assertEqual(remote.problems(repo), [])
        (repo / "mail").mkdir()
        self.assertEqual(mod.mail("ga mail read --repo mail --as W-1", str(repo)), "pinned")
        self.assertEqual(mod.mail("ga mail read --repo . --as W-1", str(repo)), "unpinned")
        self.assertEqual(mod.mail("ga mail read --repo ../mail --as W-1", str(repo / "mail")), "pinned")
        self.assertIsNone(mod.mail("ls", str(repo)))

    def test_bad_config_is_refused(self):
        for kw in ({"guard_ref": "origin"}, {"guard_ref": "origin/../x"}, {"hub": "a'b"}, {"channel_repo": "a b"},
                   {"fetch_every_min": 0}):
            with self.subTest(kw=kw):
                with self.assertRaises(ValueError):
                    remote.files("W1", **kw)

    def test_conf_edit_is_caught(self):
        repo, _ = self.load()
        g = repo / "ops/rlo/guard.py"
        g.write_text(g.read_text().replace('"fetch_every_s":300', '"fetch_every_s":0'))
        self.assertTrue(any("CONF is off the preset" in p for p in remote.problems(repo)), remote.problems(repo))
        g.write_text(g.read_text().replace('"fetch_every_s":0', '"fetch_every_s":300').replace(
            '"outbox":".ga/mailbox/outbox"', '"outbox":".ga/elsewhere"'))
        self.assertTrue(any("the outbox is" in p for p in remote.problems(repo)), remote.problems(repo))
        g.write_text(g.read_text().replace('"outbox":".ga/elsewhere"', '"outbox":".ga/mailbox/outbox"').replace(
            "def main():", "def main():  # changed"))
        self.assertTrue(any("guard.py differs" in p for p in remote.problems(repo)))

    def test_guard_runs_on_the_oldest_python_here(self):
        """guard.py runs with whatever python3 the worker has: it must at least compile on 3.8+ syntax we test."""
        repo, _ = self.load()
        compile((repo / "ops/rlo/guard.py").read_text(), "guard.py", "exec")


if __name__ == "__main__":
    unittest.main()
